### ISSUE TITLE
Getting Uncaught TypeError: Cannot read properties of undefined (

### ISSUE THREAD

**Issue by jorper98** [KanizoRGB/Imagecarousell-for-a-website#1]
Two things: 
1) File name: reference in HTML  
`<script src="imagecarousel.js"></script>` is not correct.   should have 2 letter L
`<scriptsrc="imagecarousel.js"></script>'

2) Placed 3 photos in folder.     image1.jpg, image2.jpg
     Unfortunatelly,  Images display, but not in carousel format.    
Looked inside and the following error  shows:
JavaScript:  imagecarousell.js:40      
       Uncaught TypeError: Cannot read properties of undefined (reading 'style')

Any ideas?

**Comment by andrewrgarcia** [comment]
Hi @KanizoRGB, 
This issue was corrected with the most recent merge from my pull request. You close the issue.

**Comment by KanizoRGB** [comment]
Thank you @andrewrgarcia
